groups:
  - id: domicilios_tipo_ocupado
    title: "Tipo de Domicílio Ocupado"
    description: "Distribuição de domicílios ocupados por tipo"
    columns:
      - "Domicílios Particulares Permanentes Ocupados"
      - "Domicílios Particulares Improvisados Ocupados"
      - "Unidades de Habitação em Domicílios Coletivos Com Morador"
    chart: "pie"

  - id: dppo_qtd_moradores
    title: "Quantidade de Moradores — Domicílios Particulares Permanentes Ocupados"
    description: "Nº de moradores no domicílio (DPPO)"
    columns:
      - "Domicílios Particulares Permanentes Ocupados, Com 1 morador no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, Com 2 moradores no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, Com 3 moradores no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, Com 4 moradores no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, Com 5 moradores no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, Com 6 moradores no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, Com 7 moradores no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, Com 8 moradores no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, Com 9 moradores no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, Com 10 ou mais moradores no domicílio"
    chart: "bar"

  - id: dppo_tipo_especie
    title: "Tipo de Espécie — Domicílios Particulares Permanentes Ocupados"
    description: "Tipo de espécie do domicílio (DPPO)"
    columns:
      - "Domicílios Particulares Permanentes Ocupados, Tipo de espécie é casa"
      - "Domicílios Particulares Permanentes Ocupados, Tipo de espécie é casa de vila ou em condomínio"
      - "Domicílios Particulares Permanentes Ocupados, Tipo de espécie é apartamento"
      - "Domicílios Particulares Permanentes Ocupados, Tipo de espécie é habitação em casa de cômodos ou cortiço"
      - "Domicílios Particulares Permanentes Ocupados, Tipo de espécie é habitação indígena sem paredes ou maloca"
      - "Domicílios Particulares Permanentes Ocupados, Tipo de espécie é estrutura residencial permanente degradada ou inacabada"
    chart: "bar"

  - id: dppo_abastecimento_agua
    title: "Forma de Abastecimento de Água — Domicílios Particulares Permanentes Ocupados"
    description: "Forma de abastecimento de água (DPPO)"
    columns:
      - "Domicílios Particulares Permanentes Ocupados, Utiliza rede geral de distribuição"
      - "Domicílios Particulares Permanentes Ocupados, Utiliza poço profundo ou artesiano"
      - "Domicílios Particulares Permanentes Ocupados, Utiliza poço raso, freático ou cacimba"
      - "Domicílios Particulares Permanentes Ocupados, Utiliza fonte, nascente ou mina"
      - "Domicílios Particulares Permanentes Ocupados, Utiliza carro-pipa"
      - "Domicílios Particulares Permanentes Ocupados, Utiliza água da chuva armazenada"
      - "Domicílios Particulares Permanentes Ocupados, Utiliza rios, açudes, córregos, lagos e igarapés"
      - "Domicílios Particulares Permanentes Ocupados, Utiliza outra forma de abastecimento de água"
    chart: "bar"

  - id: dppo_agua_encanada
    title: "Água Encanada — Domicílios Particulares Permanentes Ocupados"
    description: "Situação da água encanada (DPPO)"
    columns:
      - "Domicílios Particulares Permanentes Ocupados, Água chega encanada até dentro da casa, apartamento ou habitação"
      - "Domicílios Particulares Permanentes Ocupados, Água chega encanada, mas apenas ao terreno"
      - "Domicílios Particulares Permanentes Ocupados, Água não chega encanada ao domicílio"
    chart: "pie"

  - id: dppo_banheiro_tipo
    title: "Banheiro/Sanitário — Domicílios Particulares Permanentes Ocupados"
    description: "Tipo de instalação sanitária (DPPO)"
    columns:
      - "Domicílios Particulares Permanentes Ocupados, 1 banheiro de uso exclusivo com chuveiro e vaso sanitário existentes no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, 2 banheiros de uso exclusivo com chuveiro e vaso sanitário existentes no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, 3 banheiros de uso exclusivo com chuveiro e vaso sanitário existentes no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, 4 ou mais banheiros de uso exclusivo com chuveiro e vaso sanitário existentes no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, Apenas banheiro de uso comum a mais de um domicílio"
      - "Domicílios Particulares Permanentes Ocupados, Apenas sanitário ou buraco para dejeções, inclusive os localizados no terreno"
      - "Domicílios Particulares Permanentes Ocupados, Não tinham banheiro nem sanitário"
    chart: "bar"

  - id: dppo_destinacao_esgoto
    title: "Destinação do Esgoto — Domicílios Particulares Permanentes Ocupados"
    description: "Destinação do esgoto do banheiro/sanitário (DPPO)"
    columns:
      - "Domicílios Particulares Permanentes Ocupados, Destinação do esgoto do banheiro ou sanitário ou buraco para dejeções é rede geral ou pluvial"
      - "Domicílios Particulares Permanentes Ocupados, Destinação do esgoto do banheiro ou sanitário ou buraco para dejeções é fossa séptica ou fossa filtro ligada à rede"
      - "Domicílios Particulares Permanentes Ocupados, Destinação do esgoto do banheiro ou sanitário ou buraco para dejeções é fossa séptica ou fossa filtro não ligada à rede"
      - "Domicílios Particulares Permanentes Ocupados, Destinação do esgoto do banheiro ou sanitário ou buraco para dejeções é fossa rudimentar ou buraco"
      - "Domicílios Particulares Permanentes Ocupados, Destinação do esgoto do banheiro ou sanitário ou buraco para dejeções é vala"
      - "Domicílios Particulares Permanentes Ocupados, Destinação do esgoto do banheiro ou sanitário ou buraco para dejeções é rio, lago, córrego ou mar"
      - "Domicílios Particulares Permanentes Ocupados, Destinação do esgoto do banheiro ou sanitário ou buraco para dejeções é outra forma"
      - "Domicílios Particulares Permanentes Ocupados, Destinação do esgoto inexistente, pois não tinham banheiro nem sanitário"
    chart: "bar"

  - id: dppo_destino_lixo
    title: "Destino do Lixo — Domicílios Particulares Permanentes Ocupados"
    description: "Destino do lixo (DPPO)"
    columns:
      - "Domicílios Particulares Permanentes Ocupados, Lixo coletado no domicílio por serviço de limpeza"
      - "Domicílios Particulares Permanentes Ocupados, Lixo depositado em caçamba de serviço de limpeza"
      - "Domicílios Particulares Permanentes Ocupados, Lixo queimado na propriedade"
      - "Domicílios Particulares Permanentes Ocupados, Lixo enterrado na propriedade"
      - "Domicílios Particulares Permanentes Ocupados, Lixo jogado em terreno baldio, encosta ou área pública"
      - "Domicílios Particulares Permanentes Ocupados, Outro destino do lixo"
    chart: "bar"

  - id: dppo_qtd_banheiros
    title: "Quantidade de Banheiros — Domicílios Particulares Permanentes Ocupados"
    description: "Quantidade de banheiros com chuveiro e vaso (DPPO)"
    columns:
      - "Domicílios Particulares Permanentes Ocupados, 1 banheiro de uso exclusivo com chuveiro e vaso sanitário existentes no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, 2 banheiros de uso exclusivo com chuveiro e vaso sanitário existentes no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, 3 banheiros de uso exclusivo com chuveiro e vaso sanitário existentes no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, 4 banheiros de uso exclusivo com chuveiro e vaso sanitário existentes no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, 5 banheiros de uso exclusivo com chuveiro e vaso sanitário existentes no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, 6 banheiros de uso exclusivo com chuveiro e vaso sanitário existentes no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, 7 banheiros de uso exclusivo com chuveiro e vaso sanitário existentes no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, 8 banheiros de uso exclusivo com chuveiro e vaso sanitário existentes no domicílio"
      - "Domicílios Particulares Permanentes Ocupados, 9 ou mais banheiros de uso exclusivo com chuveiro e vaso sanitário existentes no domicílio"
    chart: "bar"

  - id: dppo_banheiro_exclusivo
    title: "Banheiro de Uso Exclusivo — Domicílios Particulares Permanentes Ocupados"
    description: "Presença de banheiro de uso exclusivo (DPPO)"
    columns:
      - "Domicílios Particulares Permanentes Ocupados, Com banheiro de uso exclusivo com chuveiro e vaso sanitário"
      - "Domicílios Particulares Permanentes Ocupados, Sem banheiro de uso exclusivo com chuveiro e vaso sanitário"
    chart: "pie"
