# Domain config for Demografia page
age_buckets_order:
  - "0 a 4 anos"
  - "5 a 9 anos"
  - "10 a 14 anos"
  - "15 a 19 anos"
  - "20 a 24 anos"
  - "25 a 29 anos"
  - "30 a 34 anos"
  - "35 a 39 anos"
  - "40 a 44 anos"
  - "45 a 49 anos"
  - "50 a 54 anos"
  - "55 a 59 anos"
  - "60 a 64 anos"
  - "65 a 69 anos"
  - "70 anos ou mais"
columns_alias:
  nm_mun: "NM_MUN"
  cd_mun: "CD_MUN"
  cd_setor: "CD_SETOR"
  sexo: "sexo"
  faixa_etaria: "faixa_etaria"
  populacao: "populacao"
  situacao_setor: "SITUACAO"  # alias para "Situação do Setor Censitário"
  situacao_detalhada_setor: "SITUACAO_DET_TXT"  # alias para "Situação detalhada do Setor Censitário"
